### ISSUE TITLE
[Unhandled promise rejection: Error: No download object available]

### ISSUE THREAD

**Issue by alanlanglois** [wcandillon/react-native-expo-image-cache#64] opened 2018-04-20 14:05 UTC
[Unhandled promise rejection: Error: No download object available]
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:123:42 in createErrorFromErrorData
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:80:57 in <unknown>
- ... 5 more stack frames from framework internals

![image](https://user-images.githubusercontent.com/712986/39055353-4dd5dcf4-44b4-11e8-92c7-313e826d776d.png)

Updated to the 3.0.1 and got this warning. Previously I was using 2.0.2 and never seen this warning. Did you change somthing in the syntax or the way we have to handle it since the 2.0.2?

Thanks again for your help.

**Comment by wcandillon** [comment] 2018-04-20 14:16
This warning should be fixed in 3.0.2, sorry for the inconvenience!

**Comment by wcandillon** [comment] 2018-04-20 14:38
@alanlanglois please re-open if this is not fixed in `3.0.2`

**Closed by wcandillon** 2018-04-20 14:38 UTC

**Comment by alanlanglois** [comment] 2018-05-20 19:26
I've recently upgraded my project from expokit 26 to 27 and reinstall the node dependances and the problem seems to be back (using the 3.0.3)
![simulator screen shot - iphone 6 - 2018-05-20 at 21 14 48](https://user-images.githubusercontent.com/712986/40282735-f38f1d14-5c73-11e8-8dcf-41d618456725.png)

**Comment by alanlanglois** [comment] 2018-05-20 21:43
Worked after I uninstall and reinstall the app. I hope this pb wont happen when updating trough this AppStore :/

**Comment by wcandillon** [comment] 2018-05-22 05:18
I didn't get the issue when upgrading to expo 27 🤔 I also update published app to the app store from 26 to 27 and it seems to have gone smoothly. I'm not saying that there isn't a bug here but I couldn't reproduce it.
