### ISSUE TITLE
Image not showing but only preview

### ISSUE THREAD

**Issue by cklinx** [wcandillon/react-native-expo-image-cache#50] opened 2018-03-10 11:43 UTC
Hi,
i made your awesome code works as well, but are 2 days that its not working anymore (dont remember if i updated it).
I can see just the preview, the image no. 
Same problem with your example code also.

Any help is appreciated.

**Comment by cklinx** [comment] 2018-03-10 11:47
With this code i can see just the preview.

```
const preview = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";
const uri = "https://firebasestorage.googleapis.com/v0/b/react-native-e.appspot.com/o/b47b03a1e22e3f1fd884b5252de1e64a06a14126.png?alt=media&token=d636c423-3d94-440f-90c1-57c4de921641";
<Image style={{ height: 100, width: 100 }} {...{preview, uri}} />
```

**Comment by wcandillon** [comment] 2018-03-10 11:47
yes preview is a uri now: `preview={{ uri: "data:..." }}` will update the documentation

**Comment by cklinx** [comment] 2018-03-10 11:53
Oh, i try use this new code
```
const preview = { uri: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==" };

```

 but i got this error
```
[exp] Warning: Failed prop type: Invalid prop `source` supplied to `Image`.

```

**Comment by alanlanglois** [comment] 2018-03-10 22:25
same here. 
Actually, it's not a warning but an error and it says:
"Error while updating property 'src' of a view managed by: RCTImageView

Type Error: expected dynamic type 'string", but had type 'object'

Sounds like the object is not "decomposed" when passed to the Image component :)

**Comment by alanlanglois** [comment] 2018-03-10 22:47
I don't see the preview props as an object looking at your code, but I guess this is not really the issue here, because the preview actually load :/
https://github.com/wcandillon/react-native-expo-image-cache/blob/master/src/Image.js

**Comment by wcandillon** [comment] 2018-03-15 08:51
Guys sorry about this issue, something is always wrong with the npm publishing, not sure what I'm missing should be fixed in `2.0.1` now.

**Comment by cklinx** [comment] 2018-03-16 08:09
It is not working after upgrade also.
Same warning and image is not showing.

Anyway thanks for your effort.

**Comment by alanlanglois** [comment] 2018-03-16 10:30
I don't have any warning using: 
        <Image style={styles.box} preview={{uri: "urltopreview}} uri={"urltopic"} />
It does load the preview (and keep it dark) but it sounds like the high quality isn't loaded (or the animation doesn't trigger). 
![image](https://user-images.githubusercontent.com/712986/37516067-41666f1e-290d-11e8-9c3b-c3b8066171f0.png)
--
using 2.0.1

**Comment by wcandillon** [comment] 2018-03-16 13:25
I'm not able to reproduce this issue with `2.0.1`. Could you provide me a code snippet I could easily try on my side?

**Comment by alanlanglois** [comment] 2018-03-16 13:44
Hi @wcandillon thanks for the fast reply. 

This is a project involving React Navigation and redux, except that no fancy code, just a simple:
` <Image style={{width: 90, height:90}} preview={{uri:"https://californiefrancaise-stock.s3.eu-central-1.amazonaws.com/production/uploads/product_image/90/square10_87ac2970-b4db-4676-8ce9-e057004c587d.jpeg"}} uri={"https://californiefrancaise-stock.s3.eu-central-1.amazonaws.com/production/uploads/product_image/90/square100_87ac2970-b4db-4676-8ce9-e057004c587d.jpeg"}></Image>`

**Comment by alanlanglois** [comment] 2018-03-16 13:53
Note that using the 1.0.6 version (and changin' what it need to be changed in preview) it works fine.

**Comment by wcandillon** [comment] 2018-03-17 17:17
@alanlanglois can you try with `2.0.2`? Sorry for the inconvenience.

**Comment by alanlanglois** [comment] 2018-03-17 19:05
@wcandillon It works! 
Thanks for this great support :)

**Closed** 2018-03-18 10:09 UTC
Labels: question

**Comment by wiloke1** [comment] 2019-05-09 17:45
I got this error in version 3.2.0
There are a few image not showing
![Untitled-2](https://user-images.githubusercontent.com/5530913/57474466-519a5e00-72bc-11e9-98c5-ca77cada2af4.jpg)
